on: push

name: Publish Nightly Packages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      name: Install Current .NET SDK
    - name: Add NuGet Source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
    - name: Pack Packages
      run: dotnet pack Funcky/Funcky.csproj -c Release --output nupkg --version-suffix "-nightly.${{github.sha}}"
    - name: Push Package
      run: dotnet nuget push --source github nupkg/Funcky.*.nupkg
